
version: '3'
services:
  # PICTSHARE
  # PUBLIC IMAGE/FILE HOSTING SERVICE
  # Typically accessible via http[s?]://img.domain.com
  # Reference the sample.env file for environment variables
  pictshare:
    container_name: labstack-pictshare
    image: hascheksolutions/pictshare
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 4778:80
    environment:
      URL: ${PICTSHARE_URL}
      TITLE: ${PICTSHARE_TITLE}
      LOG_UPLOADER: ${PICTSHARE_LOG_UPLOADER}
      FFMPEG_BINARY: ${PICTSHARE_FFMPEG_BINARY}
      PNG_COMPRESSION: ${PICTSHARE_PNG_COMPRESSION}
      JPEG_COMPRESSION: ${PICTSHARE_JPEG_COMPRESSION}
      WEBP_COMPRESSION: ${PICTSHARE_WEBP_COMPRESSION}
      MASTER_DELETE_CODE: ${PICTSHARE_MASTER_DELETE_CODE}
      MASTER_DELETE_IP: ${PICTSHARE_MASTER_DELETE_IP}
      UPLOAD_FORM_LOCATION: ${PICTSHARE_UPLOAD_FORM_LOCATION}
      ALLOWED_SUBNET: ${PICTSHARE_ALLOWED_SUBNET}
      ALWAYS_WEBP: ${PICTSHARE_ALWAYS_WEBP}
      UPLOAD_CODE: ${PICTSHARE_UPLOAD_CODE}
      REDIS_SERVER: ${PICTSHARE_REDIS_SERVER}
      UPLOAD_QUOTA: ${PICTSHARE_UPLOAD_QUOTA}
      MAX_RESIZED_IMAGES: ${PICTSHARE_MAX_RESIZED_IMAGES}
      MAX_UPLOAD_SIZE: ${PICTSHARE_MAX_UPLOAD_SIZE}
      ENCRYPTION_KEY: ${PICTSHARE_ENCRYPTION_KEY}
      S3_BUCKET: ${PICTSHARE_S3_BUCKET}
      S3_ACCESS_KEY: ${PICTSHARE_S3_ACCESS_KEY}
      S3_SECRET_KEY: ${PICTSHARE_S3_SECRET_KEY}
      S3_ENDPOINT: ${PICTSHARE_S3_ENDPOINT}
      S3_REGION: ${PICTSHARE_S3_REGION}
      FTP_SERVER: ${PICTSHARE_FTP_SERVER}
      FTP_PORT: ${PICTSHARE_FTP_PORT}
      FTP_SSL: ${PICTSHARE_FTP_SSL}
      FTP_USER: ${PICTSHARE_FTP_USER}
      FTP_PASS: ${PICTSHARE_FTP_PASS}
      FTP_BASEDIR: ${PICTSHARE_FTP_BASEDIR}
      FTP_PASSIVEMODE: ${PICTSHARE_FTP_PASSIVEMODE}
    volumes:
      - '/mnt/docker/data/pictshare:/var/www/data'
      
  # HASTEBIN
  # PUBLIC CODE/TEXT BIN HOSTING SERVICE
  # Typically accessible via http[s?]://gist.domain.com
  # Reference the sample.env file for environment variables
  hastebin:
    container_name: labstack-hastebin
    image: rlister/hastebin
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 4777:7777
    volumes:
      - '/mnt/docker/data/hastebin:/app/data'

  # VERDACCIO
  # PRIVATE NPM REGISTRY/CACHE
  # typically accessible via http[s?]://npm.domain.com
  # Reference the sample.env file for environment variables
  verdaccio:
    container_name: labstack-verdaccio
    image: verdaccio/verdaccio
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 4779:4873
    environment: 
      VERDACCIO_PUBLIC_URL: ${VERDACCIO_PUBLIC_URL}
      VERDACCIO_USER_UID: ${VERDACCIO_USER_UID}
    volumes:
      - '/mnt/docker/data/verdaccio/storage:/verdaccio/storage'


  # GHOST
  # GHOST BLOGGING SYSTEM
  # typically accessible via http[s?]://blog.domain.com
  # Reference the sample.env file for environment variables
  ghost:
    container_name: labstack-ghost
    image: ghost:latest
    restart: unless-stopped
    ports:
      - 4801:2368
    environment:
      # see https://ghost.org/docs/config/#configuration-options
      database__client: ${GHOST_DATABASE_CLIENT}
      database__connection__host: ${GHOST_DATABSE_HOST}
      database__connection__user: ${GHOST_DATABASE_USER}
      database__connection__password: ${GHOST_DATABASE_PASSWORD}
      database__connection__database: ${GHOST_DATABASE_NAME}
      # this url value is just an example, and is likely wrong for your environment!
      url: ${GHOST_URL}
    volumes:
      - '/mnt/docker/data/ghost/content:/var/lib/ghost/content'
    depends_on:
      - mysql

  # SATISFACTORY-SERVER
  # PRIVATE SATISFACTORY GAME SERVER
  # typically accessible via satis1.domain.com
  # Reference the sample.env file for environment variables
  satisfactory:
    container_name: labstack-satisfactory
    image: wolveix/satisfactory-server:latest
    restart: unless-stopped
    ports:
      - 7777:7777/udp
      - 15000:15000/udp
      - 15777:15777/udp
    volumes:
      - '/mnt/docker/data/satisfactory/config:/config'
    environment:
      MAXPLAYERS: ${SATISFACTORY_MAXPLAYERS}
      PGID: ${SATISFACTORY_PGID}
      PUID: ${SATISFACTORY_PUID}
      STEAMBETA: ${SATISFACTORY_STEAMBETA}
    deploy:
      resources:
        limits:
          memory: 16G
        reservations:
          memory: 12G

  # POSTGRESQL
  postgres:
    container_name: labstack-postgres
    image: postgres:latest
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - '/mnt/docker/data/postgres/:/var/lib/postgresql/data/'
      
  # MYSQL
  mysql:
    container_name: labstack-mysql
    image: mysql:8.0
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - '/mnt/docker/data/mysql:/var/lib/mysql'
  
  # REDIS
  redis:
    container_name: labstack-redis
    image: redis:latest
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - '/mnt/docker/data/redis:/data'
